EDUCATION_SECTION_CHOICES = [
    ('osnovnye-svedeniya', 'Основные сведения'),
    ('struktura-upravleniya', 'Структура и органы управления образовательной организацией'),
    ('documents', 'Документы'),
    ('obrazovanie', 'Образование'),
    ('administratsiya', 'Руководство'),
    ('prepodavateli', 'Педагогический (научно-педагогический) состав'),
    ('materialno-tehnicheskoe-obespechenie', 'Материально-техническое обеспечение и оснащенность образовательного процесса'),
    ('platnye-obr-uslugi', 'Платные образовательные услуги'),
    ('finansovo-hozyaystvennaya-deyatelnost', 'Финансово-хозяйственная деятельность'),
    ('vakantnye-mesta', 'Вакантные места для приёма (перевода)'),
    ('dostupnaya-sreda', 'Доступная среда'),
    ('stipendii', 'Стипендии и меры поддержки обучающихся'),
    ('mezhdunarodnoye', 'Международное сотрудничество'),
    ('pitanie', 'Организация питания в образовательной организации'),
]
