# Generated by Django 3.2.16 on 2026-07-14 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0056_delete_classschedulealert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassScheduleAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('psychology', 'Психология'), ('medicine', 'Медицина')], max_length=20, verbose_name='Предмет')),
                ('notified_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedule_alerts', to='content.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Уведомление об устаревшем расписании',
                'verbose_name_plural': 'Уведомления об устаревшем расписании',
            },
        ),
        migrations.AddConstraint(
            model_name='classschedulealert',
            constraint=models.UniqueConstraint(fields=('department', 'subject'), name='unique_class_schedule_alert'),
        ),
    ]
