# Generated by Django 3.2.16 on 2026-09-08 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0056_delete_classschedulealert'),
        ('schedule_alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEndingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('psychology', 'Психология'), ('medicine', 'Медицина')], max_length=20, verbose_name='Предмет')),
                ('last_date', models.DateField(verbose_name='Дата последнего занятия')),
                ('notified_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_ending_alerts', to='content.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Предупреждение об окончании расписания',
                'verbose_name_plural': 'Предупреждения об окончании расписания',
                'ordering': ['-notified_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoEventAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('started', 'Акция стартовала'), ('ending', 'Акция заканчивается')], max_length=10, verbose_name='Событие')),
                ('event_date', models.DateField(verbose_name='Дата события (starts_at / expires_at)')),
                ('notified_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_event_alerts', to='content.announcement', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Уведомление о событии акции',
                'verbose_name_plural': 'Уведомления о событиях акций',
                'ordering': ['-notified_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamPassedAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_alerts', to='content.examinfo', verbose_name='Экзамен')),
            ],
            options={
                'verbose_name': 'Уведомление о прошедшем экзамене',
                'verbose_name_plural': 'Уведомления о прошедших экзаменах',
            },
        ),
        migrations.CreateModel(
            name='ExamEndingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.DateField(verbose_name='Дата последнего экзамена ГИБДД')),
                ('notified_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_ending_alerts', to='content.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Предупреждение об окончании экзаменов',
                'verbose_name_plural': 'Предупреждения об окончании экзаменов',
                'ordering': ['-notified_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='scheduleendingalert',
            constraint=models.UniqueConstraint(fields=('department', 'subject', 'last_date'), name='unique_schedule_ending_alert'),
        ),
        migrations.AddConstraint(
            model_name='promoeventalert',
            constraint=models.UniqueConstraint(fields=('announcement', 'event_type', 'event_date'), name='unique_promo_event_alert'),
        ),
        migrations.AddConstraint(
            model_name='exampassedalert',
            constraint=models.UniqueConstraint(fields=('exam',), name='unique_exam_passed_alert'),
        ),
        migrations.AddConstraint(
            model_name='examendingalert',
            constraint=models.UniqueConstraint(fields=('department', 'last_date'), name='unique_exam_ending_alert'),
        ),
    ]
