# Generated by Django 3.2.16 on 2025-10-12 10:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Подразделение')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-часть')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug шаблона')),
            ],
            options={
                'verbose_name': 'Шаблон страницы',
                'verbose_name_plural': 'Шаблоны страниц',
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Контент')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлён')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.department', verbose_name='Подразделение')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.pagetemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Контент страницы',
                'verbose_name_plural': 'Контент страниц',
                'unique_together': {('department', 'template')},
            },
        ),
    ]
