# Generated by Django 3.2.16 on 2025-11-23 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('meta_title', models.CharField(blank=True, max_length=100, verbose_name='SEO Title')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='SEO Description')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='content.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Детали подразделения',
                'verbose_name_plural': 'Детали подразделений',
            },
        ),
    ]
