# Generated by Django 3.2.16 on 2025-11-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_departmentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentdetails',
            name='ogrn',
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='kpp',
            field=models.CharField(blank=True, max_length=15, verbose_name='КПП'),
        ),
    ]
