# Generated by Django 3.2.16 on 2025-11-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20251123_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageContent',
        ),
        migrations.DeleteModel(
            name='PageTemplate',
        ),
    ]
