# Generated by Django 3.2.16 on 2025-11-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='department',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Выберите, в каких подразделениях будет отображаться этот пункт. Оставьте пустым — чтобы показывать во всех.', related_name='menu_items', to='content.Department', verbose_name='Подразделения'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(max_length=200, verbose_name='URL (относительный)'),
        ),
    ]
