# Generated by Django 3.2.16 on 2025-11-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_news_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='joomla_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID из Joomla'),
        ),
    ]
