# Generated by Django 3.2.16 on 2025-11-24 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_news_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория документа',
                'verbose_name_plural': 'Категории документов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл (PDF/изображение)')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Изображение')], editable=False, max_length=10, verbose_name='Тип файла')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок в категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='content.documentcategory', verbose_name='Категория')),
                ('departments', models.ManyToManyField(blank=True, help_text='Подразделения, где отображается документ. Если пусто — везде.', related_name='documents', to='content.Department')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['category__order', 'order', 'title'],
            },
        ),
    ]
