# Generated by Django 3.2.16 on 2025-11-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_document_documentcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['department', 'category__order', 'order', 'title'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='departments',
        ),
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='content.department', verbose_name='Подразделение'),
            preserve_default=False,
        ),
    ]
