# Generated by Django 3.2.16 on 2025-11-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20251124_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('file', 'Файл (PDF/изображение)'), ('external', 'Внешняя ссылка'), ('info', 'Информационный пункт (без файла)')], default='file', max_length=10, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='document',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('image', 'Изображение')], max_length=10, verbose_name='Тип файла'),
        ),
    ]
