# Generated by Django 3.2.16 on 2025-12-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20251124_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentdetails',
            name='bank',
            field=models.TextField(blank=True, verbose_name='Банк получателя'),
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='bik',
            field=models.CharField(blank=True, max_length=9, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='corr_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Корр. счёт'),
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='map_iframes',
            field=models.JSONField(blank=True, default=list, verbose_name='Ссылки на карты (Google Embed)'),
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='payment_purpose',
            field=models.CharField(blank=True, max_length=300, verbose_name='Назначение платежа'),
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Наименование получателя'),
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='schedule',
            field=models.JSONField(blank=True, default=list, verbose_name='Режим работы'),
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='settlement_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Расч. счёт'),
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='short_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Короткий адрес'),
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='show_contacts',
            field=models.BooleanField(default=True, verbose_name='Показывать контакты'),
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='show_latest_news',
            field=models.BooleanField(default=True, verbose_name='Показывать последние новости'),
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='show_partners',
            field=models.BooleanField(default=False, verbose_name='Показывать партнёров'),
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='show_services',
            field=models.BooleanField(default=False, verbose_name='Показывать услуги'),
        ),
    ]
