# Generated by Django 3.2.16 on 2025-12-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20251213_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentdetails',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='departmentdetails',
            name='longitude',
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='map_center',
            field=models.JSONField(blank=True, default=list, help_text='Пример: [52.267482, 104.310026]', verbose_name='Координаты центра (широта, долгота)'),
        ),
    ]
