# Generated by Django 3.2.16 on 2025-12-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20251213_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='display_in_sections',
            field=models.JSONField(blank=True, default=list, help_text='Выберите разделы, где документ будет отображаться', verbose_name='Отображать в разделах'),
        ),
    ]
