# Generated by Django 3.2.16 on 2025-12-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_document_display_in_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentdetails',
            name='show_documents',
            field=models.BooleanField(default=True, verbose_name='Показывать документы'),
        ),
    ]
