# Generated by Django 3.2.16 on 2025-12-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Например: "taxi", "insurance", "appraisal"', max_length=50, verbose_name='Имя иконки (без расширения)'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('parking', 'Автостоянка'), ('info_card', 'Информационная карточка (с описанием)'), ('custom', 'Произвольная услуга')], default='info_card', max_length=20, verbose_name='Тип услуги'),
        ),
    ]
