# Generated by Django 3.2.16 on 2025-12-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20251213_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_block_id',
            field=models.CharField(blank=True, help_text='Например: "insurance-desc", "taxi-desc"', max_length=50, verbose_name='ID блока описания'),
        ),
    ]
