# Generated by Django 3.2.16 on 2025-12-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_service_description_block_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='points',
            field=models.JSONField(blank=True, default=list, help_text='Пример: ["Автостраховка ОСАГО", "Автостраховка КАСКО"]', verbose_name='Пункты (список строк)'),
        ),
    ]
