# Generated by Django 3.2.16 on 2025-12-14 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('heading', 'Заголовок'), ('paragraph', 'Абзац'), ('list', 'Список'), ('image', 'Изображение'), ('video', 'Видео'), ('quote', 'Цитата')], max_length=20, verbose_name='Тип блока')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('items', models.JSONField(blank=True, default=list, verbose_name='Элементы списка')),
                ('image', models.ImageField(blank=True, upload_to='materials/images/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, upload_to='materials/videos/', verbose_name='Видео')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео (YouTube/Vimeo)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='content.material')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
