# Generated by Django 3.2.16 on 2025-12-14 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_contentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_services', to='content.material', verbose_name='Материал с описанием'),
        ),
    ]
