# Generated by Django 3.2.16 on 2025-12-14 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_service_description_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
    ]
