# Generated by Django 3.2.16 on 2025-12-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_remove_service_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='content',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_block_id',
        ),
    ]
