# Generated by Django 3.2.16 on 2025-12-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_auto_20251214_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_partner_news',
            field=models.BooleanField(default=False, help_text='Если отмечено — новость НЕ будет показываться в ленте новостей, а только в блоке "Наши партнёры".', verbose_name='Партнёрская новость (отображается в секции "Партнёры")'),
        ),
    ]
