# Generated by Django 3.2.16 on 2025-12-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_news_is_partner_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст новости'),
        ),
    ]
