# Generated by Django 3.2.16 on 2025-12-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentdetails',
            name='show_main_decor',
            field=models.BooleanField(default=False, verbose_name='Показывать главный декор'),
        ),
    ]
