# Generated by Django 3.2.16 on 2025-12-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_departmentdetails_show_main_decor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentdetails',
            name='show_main_decor',
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='show_exam_info',
            field=models.BooleanField(default=False, verbose_name='Показывать акции и экзамены'),
        ),
        migrations.AddField(
            model_name='departmentdetails',
            name='show_header_banner',
            field=models.BooleanField(default=False, verbose_name='Показывать главный баннер'),
        ),
    ]
