# Generated by Django 3.2.16 on 2025-12-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_auto_20251220_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentdetails',
            name='show_education_info',
            field=models.BooleanField(default=False, verbose_name='Показывать сведения об образовательной организации'),
        ),
    ]
