# Generated by Django 3.2.16 on 2025-12-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_auto_20251221_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='documents_section',
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('heading', 'Заголовок'), ('paragraph', 'Абзац'), ('list', 'Список'), ('image', 'Изображение'), ('video', 'Видео'), ('quote', 'Цитата')], max_length=20, verbose_name='Тип блока'),
        ),
    ]
