# Generated by Django 3.2.16 on 2025-12-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_auto_20251221_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='documents_section',
            field=models.CharField(blank=True, help_text='Например: mtob, basic_info и т.д. Должен совпадать со значениями в Document.SECTIONS', max_length=50, verbose_name='Раздел документов'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('heading', 'Заголовок'), ('paragraph', 'Абзац'), ('list', 'Список'), ('image', 'Изображение'), ('video', 'Видео'), ('quote', 'Цитата'), ('documents', 'Документы')], max_length=20, verbose_name='Тип блока'),
        ),
    ]
