# Generated by Django 3.2.16 on 2025-12-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_auto_20251221_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentdetails',
            name='show_pricing',
            field=models.BooleanField(default=False, verbose_name='Показывать стоимость'),
        ),
    ]
