# Generated by Django 3.2.16 on 2026-01-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_departmentdetails_show_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentdetails',
            name='cellphone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Сотовый телефон'),
        ),
    ]
