# Generated by Django 3.2.16 on 2026-03-15 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_departmentdetails_cellphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=50, verbose_name='Номер группы')),
                ('exam_type', models.CharField(choices=[('qualification', 'Квалификационный экзамен'), ('gibdd', 'Экзамен в ГИБДД')], max_length=30, verbose_name='Тип экзамена')),
                ('theory_date', models.DateField(verbose_name='Дата теоретического экзамена')),
                ('gibdd_date', models.DateField(blank=True, null=True, verbose_name='Дата экзамена в ГИБДД')),
                ('gibdd_time', models.TimeField(blank=True, null=True, verbose_name='Время экзамена в ГИБДД')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('auto_hide_after_date', models.BooleanField(default=True, verbose_name='Автоматически скрывать после даты экзамена')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_info', to='content.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Информация об экзамене',
                'verbose_name_plural': 'Информация об экзаменах',
                'ordering': ['department', 'theory_date', 'order'],
            },
        ),
    ]
