# Generated by Django 3.2.16 on 2026-03-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_examinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinfo',
            name='exam_type',
        ),
        migrations.AddField(
            model_name='examinfo',
            name='practice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата практического экзамена'),
        ),
    ]
