# Generated by Django 3.2.16 on 2026-03-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_auto_20260315_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examinfo',
            options={'ordering': ['gibdd_date'], 'verbose_name': 'Информация об экзамене', 'verbose_name_plural': 'Информация об экзаменах'},
        ),
        migrations.RemoveField(
            model_name='examinfo',
            name='auto_hide_after_date',
        ),
        migrations.RemoveField(
            model_name='examinfo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='examinfo',
            name='order',
        ),
    ]
