# Generated by Django 3.2.16 on 2026-03-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_auto_20260315_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examinfo',
            options={'ordering': ['group_number', 'gibdd_date'], 'verbose_name': 'Информация об экзамене', 'verbose_name_plural': 'Информация об экзаменах'},
        ),
        migrations.AlterField(
            model_name='examinfo',
            name='group_number',
            field=models.PositiveSmallIntegerField(verbose_name='Номер группы'),
        ),
    ]
