# Generated by Django 3.2.16 on 2026-03-29 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_auto_20260315_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('header_banner', 'Главный баннер'), ('exam_info', 'Акции и экзамены'), ('latest_news', 'Последние новости'), ('pricing', 'Стоимость'), ('education_info', 'Сведения об образовательной организации'), ('services', 'Услуги'), ('documents', 'Документы'), ('partners', 'Партнёры'), ('contacts', 'Контакты')], max_length=50, verbose_name='Секция')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_page_sections', to='content.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Секция главной страницы',
                'verbose_name_plural': 'Секции главной страницы',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='homepagesection',
            constraint=models.UniqueConstraint(fields=('department', 'section_key'), name='unique_home_section_per_department'),
        ),
    ]
