# Generated by Django 3.2.16 on 2026-03-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_auto_20260329_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentdetails',
            name='show_contacts',
        ),
        migrations.RemoveField(
            model_name='departmentdetails',
            name='show_documents',
        ),
        migrations.RemoveField(
            model_name='departmentdetails',
            name='show_education_info',
        ),
        migrations.RemoveField(
            model_name='departmentdetails',
            name='show_exam_info',
        ),
        migrations.RemoveField(
            model_name='departmentdetails',
            name='show_header_banner',
        ),
        migrations.RemoveField(
            model_name='departmentdetails',
            name='show_latest_news',
        ),
        migrations.RemoveField(
            model_name='departmentdetails',
            name='show_partners',
        ),
        migrations.RemoveField(
            model_name='departmentdetails',
            name='show_pricing',
        ),
        migrations.RemoveField(
            model_name='departmentdetails',
            name='show_services',
        ),
    ]
