# Generated by Django 3.2.16 on 2026-06-14 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_auto_20260329_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('info', 'Информационная карточка'), ('announcement', 'Объявление'), ('promo', 'Акция / Сертификат')], default='announcement', max_length=20, verbose_name='Тип карточки')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, help_text='Допустим HTML: <p>, <strong>, <ul>, <li>.', verbose_name='Текст (HTML)')),
                ('image', models.ImageField(blank=True, help_text='Только для типа «Акция / Сертификат».', null=True, upload_to='announcements/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='content.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Объявление / Акция',
                'verbose_name_plural': 'Объявления и акции',
                'ordering': ['order', '-id'],
            },
        ),
    ]
