# Generated by Django 3.2.16 on 2026-06-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_fix_announcement_card_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateField(blank=True, help_text='Оставьте пустым — будет показываться бессрочно.', null=True, verbose_name='Показывать до (включительно)'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='card_type',
            field=models.CharField(choices=[('info', 'Карточка в сетке (маленькая)'), ('announcement', 'Объявление (на всю ширину)'), ('promo', 'Акция / Сертификат (с изображением, на всю ширину)')], default='announcement', max_length=20, verbose_name='Тип карточки'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.TextField(blank=True, help_text='Допустим HTML-разметка: p, strong, ul, li и др.', verbose_name='Текст (HTML)'),
        ),
    ]
