# Generated by Django 3.2.16 on 2026-06-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_announcement_set_expiry_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='section_key',
            field=models.CharField(choices=[('header_banner', 'Главный баннер'), ('announcements', 'Объявления и акции'), ('exam_info', 'Экзамены и карточки'), ('latest_news', 'Последние новости'), ('pricing', 'Стоимость'), ('education_info', 'Сведения об образовательной организации'), ('services', 'Услуги'), ('documents', 'Документы'), ('partners', 'Партнёры'), ('contacts', 'Контакты')], max_length=50, verbose_name='Секция'),
        ),
    ]
