# Generated by Django 3.2.16 on 2026-06-26 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_create_announcements_homepagesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('psychology', 'Психология'), ('medicine', 'Медицина')], max_length=20, verbose_name='Предмет')),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('time_start', models.TimeField(verbose_name='Начало')),
                ('time_end', models.TimeField(verbose_name='Конец')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='content.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Занятие (психология / медицина)',
                'verbose_name_plural': 'Занятия (психология / медицина)',
                'ordering': ['date', 'time_start'],
            },
        ),
    ]
