# Generated by Django 3.2.16 on 2026-06-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0051_add_class_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='starts_at',
            field=models.DateField(blank=True, help_text='Оставьте пустым — будет показываться сразу.', null=True, verbose_name='Показывать с'),
        ),
    ]
