# Generated by Django 3.2.16 on 2026-06-26 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_announcement_starts_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_price', models.PositiveIntegerField(verbose_name='Цена теории, ₽')),
                ('practice_price_per_hour', models.PositiveIntegerField(verbose_name='Цена практики, ₽/час')),
                ('hours_mkpp', models.PositiveSmallIntegerField(default=58, verbose_name='Часов на МКПП')),
                ('hours_akpp', models.PositiveSmallIntegerField(default=56, verbose_name='Часов на АКПП')),
                ('installment_available', models.BooleanField(default=False, verbose_name='Рассрочка платежа')),
                ('promo_theory_price', models.PositiveIntegerField(blank=True, help_text='Оставьте пустым, если теория без скидки.', null=True, verbose_name='Акц. цена теории, ₽')),
                ('promo_practice_price_per_hour', models.PositiveIntegerField(blank=True, help_text='Оставьте пустым, если практика без изменений.', null=True, verbose_name='Акц. цена практики, ₽/час')),
                ('promo_starts_at', models.DateField(blank=True, null=True, verbose_name='Акция с')),
                ('promo_expires_at', models.DateField(blank=True, null=True, verbose_name='Акция до (включительно)')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plan', to='content.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Прайс-план',
                'verbose_name_plural': 'Прайс-планы',
            },
        ),
    ]
