# Generated by Django 3.2.16 on 2026-06-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0053_add_pricing_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='promo_expires_at',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='promo_practice_price_per_hour',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='promo_starts_at',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price_change_date',
            field=models.DateField(blank=True, help_text='С этой даты начнёт действовать новая цена практики.', null=True, verbose_name='Дата смены цены практики'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='scheduled_practice_price',
            field=models.PositiveIntegerField(blank=True, help_text='Цена, которая вступит в силу с указанной даты.', null=True, verbose_name='Новая цена практики, ₽/час'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='promo_theory_price',
            field=models.PositiveIntegerField(blank=True, help_text='Заполните, чтобы зачёркивать основную цену когда активно promo-объявление.', null=True, verbose_name='Цена теории по акции, ₽'),
        ),
    ]
