# Generated by Django 3.2.16 on 2026-07-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0055_add_class_schedule_alert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassScheduleAlert',
        ),
    ]
